---
title: "Data analysis"
author: "Amalie Lysgaard Andersen"
date: "14 11 2019"
output: html_document
---

# 1. Initial preprocessing
```{r load, data, include=FALSE}
library(pacman)
pacman::p_load(ggplot2, tidyverse, stringi, stringr, pie, brms)

df <-  read.csv("df_spellchecked_numbersfixed.csv")
cat <- read.csv("Categories - priority categories.csv", na.strings = c("","NA"))

# Filtering to groups
##conditions
con_b <- filter(df, condition == "B") 
con_m <- filter(df, condition == "M") 
```

```{r factor, character} 
df$chain <- as.factor(df$chain)  
df$scene <- as.factor(df$scene)
df$phase <- as.factor(df$phase)
df$generation <- as.factor(df$generation)

df$desc <- as.character(df$desc)

cat$colour <- as.character(cat$colour)
cat$pattern <- as.character(cat$pattern)
cat$landmark <- as.character(cat$landmark)
cat$direction <- as.character(cat$direction)
cat$number <- as.character(cat$number)
```



# 2. Word count in each category
```{r counts}
#Counting all words  
#df_2$direc_count <- str_count(df_2$desc, paste(na.omit(cat$direction), collapse = "|"))
#df_2$number_count <- str_count(df_2$desc, paste(na.omit(cat$number), collapse = "|"))
#df_2$colour_count <- str_count(df_2$desc, paste(na.omit(cat$colour), collapse = "|"))
#df_2$pattern_count <- str_count(df_2$desc, paste(na.omit(cat$pattern), collapse = "|"))
#df_2$landmark_count <- str_count(df_2$desc, paste(na.omit(cat$landmark), collapse = "|"))

######## Annotation scheme ########

#New df incl. cat
#df <- merge(data.frame(df, row.names=NULL), data.frame(cat, row.names=NULL), by = 0, all = TRUE)[-1]

# create list for each category with words (regular expressions where needed)
# directions
directions <- c("højre", "venstre", "ligeud", "\\bned\\b", "\\bop\\b", "bagud","ligefrem","\\bhen\\b","\\frem\\b", "fremad", "nedad", "nordøst", "skråt", "90", "180", "\\bret\\b", "klokken")
as.character(directions)
df$direc_count <- str_count(df$desc, paste(directions, collapse = "|"))


# numbers
numbers <- c("\\bén\\b","\\b2\\b","\\b5\\b","\\b4\\b","\\bet\\b","\\bførste\\b","\\banden\\b","\\bforrige\\b","\\btre\\b","\\b1\\b","\\b3\\b","\\btredje\\b","\\bfjerde\\b","\\bsidste\\b","\\bto\\b","\\b7\\b","\\b10\\b","\\b25\\b","\\b15\\b","\\b8\\b","\\bfå\\b")
as.character(numbers)
df$number_count <- str_count(df$desc, paste(numbers, collapse = "|"))


# colours 
colours <- c("rød", "grøn", "\\blilla\\b", "blå","hvid", "gul", "orange","brun")
as.character(colours)
df$colour_count <- str_count(df$desc, paste(colours, collapse = "|"))

# shapes
patterns <- c("prik", "plet", "streg", "pil", "oval","cirkler", "stjerne","firkant","trekant","kvadrat","tern","stribe","ellipse","gitter","ensfarvede","mønster")
as.character(patterns)
df$pattern_count <- str_count(df$desc, paste(patterns, collapse = "|"))


# landmarks 
landmarks <- c("væg", "blindgyde", "kasse", "åbning", "stjernevæg", "kant", "bygning", "plads", "hus", "hjørne", "tårn", "indhak", "mur", "mål", "gyde", "sidevej", "torv", "sidegade", "sidevej", "bue", "kryds", "\\brum\\b", "firkanten", "toppen", "slutningen", "endevæg", "udgang", "passage", "vindue")
as.character(landmarks)
df$landmark_count <- str_count(df$desc, paste(landmarks, collapse = "|"))
```

```{r condition + variable count}
# new variable that gathers word categories into conditions 
df$manhattan_count <- df$number_count + df$direc_count
df$barcelona_count <-  df$landmark_count + df$colour_count + df$pattern_count

# variable within conditions count
df$direc_prop <- round(((df$direc_count/df$wordcount) * 100), 3)
df$number_prop <- round(((df$number_count/df$wordcount) * 100), 3)
df$colour_prop <- round(((df$colour_count/df$wordcount) * 100), 3)
df$pattern_prop <- round(((df$pattern_count/df$wordcount) * 100), 3)
df$landmark_prop <- round(((df$landmark_count/df$wordcount) * 100), 3)

```

```{r proportion}
# removing punctualisations 
df$desc <- str_replace_all(df$desc, "[[:punct:]]", "")

# break up the description strings in each row by " " to get individual words
split <- strsplit(df$desc, split=" ")

# count the number of words as the length of the vectors
df$wordcount <- sapply(split, length)

# calculating proportion of condition words out of all words used (to account for length differences)
df$barcelona_prop <- (df$barcelona_count/df$wordcount) * 100
df$manhattan_prop <- (df$manhattan_count/df$wordcount) * 100

# decimals
df$barcelona_prop <- round(df$barcelona_prop, 3)
df$manhattan_prop <- round(df$manhattan_prop, 3)
```

```{r splitting into phases}
# subsets acc to phase 
#df_1 <- filter(df, phase == "1")
df_2 <- filter(df, phase == "2")
#df_3 <- filter(df, phase == "3")
```



# 3. Modelling
```{r example of bayesian}
get_prior(colour_prop ~ 1 + condition, data = df_2, family = gaussian()) 
 
m0.0 <- brm(
  steps ~ 1 , 
  prior = c(set_prior("normal(20, 5)", class = "Intercept"), 
            set_prior("normal(0, 10)", class = "sigma")),
  data = df
)

#calling results
m0.0
#checking divergents
pairs(m0.0, np = nuts_params(model0.0))
#plot
plot(m0.0)
#ppcheck
pp_check(m0.0, nsamples = 50) 
```

```{r plot raw data}
#plotting raw data
ggplot(df_2, aes(direc_prop)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3)

ggplot(df_2, aes(number_prop)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3)

ggplot(df_2, aes(colour_prop)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3)

ggplot(df_2, aes(direc_prop)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3)

ggplot(df_2, aes(pattern_prop)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3)

ggplot(df_2, aes(landmark_prop)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3)
```

```{r model with getprior estimates}
prior_0 = c(
  prior(normal(3, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
test_prior <- brm(colour_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_0, 
                  sample_prior = "only")

# pp-check
pp_check(test_prior, nsample = 100)

#modelling in brm
test_get <- brm(colour_prop ~ 1 + condition * generation, 
            family = gaussian, 
            df_2, 
            prior = prior_0)
test_get
plot(test_get)

#checking posterior 
pp_check(test_get, nsample = 100)
```

```{r testing dif priors}
prior_5 = c(
  prior(normal(5, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
prior_test_5 <- brm(colour_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_5, 
                  sample_prior = "only")

# pp-check
#pp_check(prior_5, nsample = 100)

#modelling in brm
model_5 <- brm(colour_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_5)
model_5
plot(model_5)

#checking posterior 
pp_check(model_5, nsample = 100)

# Prior 10
prior_10 = c(
  prior(normal(10, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
prior_test_5 <- brm(colour_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_10, 
                  sample_prior = "only")

# pp-check
#pp_check(prior_10, nsample = 100)

#modelling in brm
model_10 <- brm(colour_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_10)
model_10
plot(model_10)

#checking posterior 
pp_check(model_10, nsample = 100)


### waic
model_5 <- add_criterion(model_5, "waic")
model_10 <- add_criterion(model_10, "waic")
# compare the WAIC estimates
w1 <- loo_compare(model_5, model_10, criterion = "waic")
print(w1, simplify = F)

#Calculating weights
model_weights(model_5, model_10, weights = "waic") %>% 
  round(digits = 2)
```

- Distribution: gaussian
- Priors set
  - Intercept(5,5)
  - Beta(0,5)
  - Sigma(0,5)

First try
```{r col, cond and gen}
#defining priors
prior_1 = c(
  prior(normal(0, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
test_prior <- brm(colour_prop ~ 1 + condition * generation, 
                  family = "normal", 
                  df_2, 
                  prior = prior_1, 
                  sample_prior = "only")

# pp-check
pp_check(test_prior, nsample = 100)

#modelling in brm
test <- brm(colour_prop ~ 1 + condition * generation, 
            family = gaussian, 
            df_2, 
            prior = prior_1)
test
plot(test)

#checking posterior 
pp_check(test, nsample = 100)
```

Real models
```{r direc and cond} 
#defining priors  
prior_test = c(
  prior(normal(5, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
direc_prior <- brm(direc_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(direc_prior, nsample = 100)

#modelling in brm
direc1 <- brm(direc_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_test)
direc1
plot(direc1)
pairs(direc1, np = nuts_params(direc1))

#checking posterior 
pp_check(direc1, nsample = 100)

```

```{r number and cond}
#defining priors 
prior_test = c( 
  prior(normal(5, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
number_prior <- brm(number_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(number_prior, nsample = 100)

#modelling in brm
number1 <- brm(number_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_test)
number1
plot(number1)

#checking posterior 
pp_check(number1, nsample = 100)
```

```{r col and cond} 
#defining priors 
prior_test = c(
  prior(normal(5, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
col_prior <- brm(colour_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(col_prior, nsample = 100)

#modelling in brm
colour1 <- brm(colour_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_test)
colour1
plot(colour1)

#checking posterior 
pp_check(colour1, nsample = 100)

```

```{r pattern and cond} 
#defining priors
prior_test = c(
  prior(normal(5, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
pattern_prior <- brm(pattern_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(pattern_prior, nsample = 100)

#modelling in brm
pattern1 <- brm(pattern_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_test)
pattern1
plot(pattern1)

#checking posterior 
pp_check(pattern1, nsample = 100)
 
```

```{r landmark and cond}
#defining priors
prior_test = c( 
  prior(normal(5, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
landmark_prior <- brm(landmark_prop ~ 1 + condition, 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(landmark_prior, nsample = 100)

#modelling in brm
landmark1 <- brm(landmark_prop ~ 1 + condition, 
            family = gaussian, 
            df_2, 
            prior = prior_test)
landmark1
plot(landmark1)

#checking posterior 
pp_check(landmark1, nsample = 100)
```




Testers
```{r direc and count}
#defining priors
prior_test = c(
  prior(normal(0, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
direc2_prior <- brm(direc_count ~ 1 + condition + generation, 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(direc2_prior, nsample = 100)

#modelling in brm
direc2 <- brm(direc_count ~ 1 + condition + generation, 
            family = gaussian, 
            df_2, 
            prior = prior_test)
direc2
plot(direc2)

#checking posterior 
pp_check(direc2, nsample = 100)

```

```{r with id as random slope}
#defining priors
prior_test = c(
  prior(normal(0, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 5), class = 'sd'),
  prior(normal(0, 10), class = 'sigma')
)

# predictive prior check
test_prior <- brm(colour_prop ~ 1 + condition * generation + (1 | ID), 
                  family = "normal", 
                  df_2, 
                  prior = prior_test, 
                  sample_prior = "only")

# pp-check
pp_check(test_prior, nsample = 100)

#modelling in brm
test <- brm(colour_prop ~ 1 + condition * generation + (1 | ID), 
            family = gaussian, 
            df_2, 
            prior = prior_test)
test
plot(test)

#checking posterior
pp_check(test, nsample = 100)



```


WAIC
```{r adding waic criterion for all models}
direc1 <- add_criterion(direc1, "waic") 
number1 <- add_criterion(number1, "waic")
colour1 <- add_criterion(colour1, "waic")
pattern1 <- add_criterion(pattern1, "waic")
landmark1 <- add_criterion(landmark1, "waic")
```

```{r waic}
# compare the WAIC estimates
w1 <- loo_compare(direc1, number1, colour1, pattern1, landmark1, criterion = "waic")
print(w1, simplify = F)

#Calculating weights
model_weights(direc1, number1, colour1, pattern1, landmark1, weights = "waic") %>% 
  round(digits = 2)
```



# 4. Plots
- Idea: radar plot in ggplot
```{r initial plots}

ggplot(df_2, aes()) +
  geom_histogram(aes(manhattan_count)) +
  facet_wrap(~barcelona_count)

ggplot(df_2, aes(manhattan_count, barcelona_count)) +
  geom_histogram()


ggplot(df_2, aes(x = manhattan_count)) +
  geom_bar(aes(y = barcelona_count)) 


plot1 <- ggplot(moraldata, aes(x = framing, y = choice)) +
  geom_bar(stat = "summary", fun.data = mean_cl_boot, width = 0.5, aes(fill = framing)) +
  facet_wrap(~scenario) +
  labs(x = "Answer", y = "Count", title = "Count of answers in the two conditions") +
  theme(legend.position = "none")

plot1
plot(data)



```


```{r}

```





